apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-actions-runner
  namespace: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: workdir
        hostPath:
          path: /tmp/github-runner-your-repo
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: ACCESS_TOKEN
          value: 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
        # - name: RUNNER_SCOPE
        #   value: "org"
        # - name: ORG_NAME
        #   value: coscq
        - name: LABELS
          value: docker-local,glab-actions-runner
        - name: RUNNER_TOKEN
          value: BCGIEPSAFDSOWGEPBKHWPI3E56N4U
        - name: REPO_URL
          value: https://github.com/coscq/glab-actions
        - name: RUNNER_NAME_PREFIX
          value: docker-github-local-runner
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUNNER_WORKDIR
          value: /tmp/github-runner-your-repo
        - name: RUNNER_GROUP
          value: default
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: workdir
          mountPath: /tmp/github-runner-your-repo
