name: hello-world
on: push
jobs:
  my-job:
    runs-on: docker-local
    steps:
      - name: install terraform
        run: .github/scripts/terraform-install.sh
        shell: bash
      - name: terraform version
        run: terraform version