name: hello-world
on: push
jobs:
  my-job:
    runs-on: docker-local
    steps:
      # - name: install terraform
      #   run: |
      #       apt update && apt install -y wget unzip
      #       cd /tmp && wget https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
      #       unzip terraform_1.5.6_linux_amd64.zip && cp terraform /usr/bin
      - name: terraform version
        env:
          credentials: ${{ secrets.KUBECONFIG }}
        run: export